name: challenge_for_t_pop
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.2.0
  flutter_lints: 2.0.0
  json_serializable: 6.3.1

flutter:
  uses-material-design: true